name: manage-azure-policy-91cbf011
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_SQL_Database_to_Event_Hub_9a7c7a7d-49e5-4213-bea8-6a502b6272e0/**'
#      - .github/workflows/manage-azure-policy-91cbf011.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_91cbf011}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_Diagnostic_Settings_for_Azure_SQL_Database_to_Event_Hub_9a7c7a7d-49e5-4213-bea8-6a502b6272e0/**
